// Generated by CoffeeScript 1.7.1
require.config({
  baseUrl: '../js',
  paths: {
    text: 'vendor/text',
    jquery: 'vendor/jquery.min',
    underscore: 'vendor/underscore.min',
    backbone: 'vendor/backbone.min',
    bootstrap: 'vendor/bootstrap.min',
    templates: '../templates',
    collections: './collections',
    models: './models',
    views: './views'
  },
  shim: {
    bootstrap: {
      deps: ['jquery']
    }
  }
});

define(function(require, exports, module) {
  var $, Router, bootstrap, router;
  $ = require('jquery');
  Router = require('./router');
  bootstrap = require('bootstrap');
  return router = new Router();
});
