// Generated by CoffeeScript 1.7.1
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(function(require, exports, module) {
  var $, Backbone, Release, ReleaseView, _;
  $ = require('jquery');
  _ = require('underscore');
  Backbone = require('backbone');
  Release = require('models/release');
  return ReleaseView = (function(_super) {
    __extends(ReleaseView, _super);

    function ReleaseView() {
      return ReleaseView.__super__.constructor.apply(this, arguments);
    }

    return ReleaseView;

  })(Backbone.View(function() {
    return {
      el: '.modal-content',
      render: function(slug) {
        var release;
        release = new Release(slug);
        return release.fetch({
          success: (function(_this) {
            return function(model, data) {
              return console.log(model);
            };
          })(this)
        });
      }
    };
  }));
});
