// Generated by CoffeeScript 1.7.1
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(function(require, exports, module) {
  var Backbone, Release, Releases;
  Backbone = require('backbone');
  Release = require('models/release');
  return Releases = (function(_super) {
    __extends(Releases, _super);

    function Releases() {
      return Releases.__super__.constructor.apply(this, arguments);
    }

    Releases.prototype.model = Release;

    Releases.prototype.url = 'api/releases';

    return Releases;

  })(Backbone.Collection);
});
